# Docker Hub 에 올려진 node:10.15.3 이미지를 base 이미지로 사용하겠다.
FROM node:10.15.3

# 관리자는 cocoroocoo 이다.
MAINTAINER cocoroocoo

# 백엔드 환경 구성
# 백엔드 작업 폴더를 기존 폴더에서 도커 안으로 복사해서 생성
COPY back /gallery_app/back

# 도커에서 백엔드 관련 명령어 돌릴 디렉토리 지정
WORKDIR /gallery_app/back/

# 백엔드 관련 명령어 실행 : 
# RUN npm install -> 이걸 .sh로 뺌

# .sh파일을 워크 디렉토리 안으로 복사
COPY compose/express/start-dev.sh /start-dev.sh

# 복사한 .sh파일에 권한 부여
RUN chmod +x /*.sh